# Generated by Django 4.0.3 on 2022-05-30 23:08

from django.db import migrations, models
import django.db.models.deletion
import efile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('no_int', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('no_ext', models.CharField(max_length=255)),
                ('suburb', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Direccion',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='BloodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de sangre',
                'verbose_name_plural': 'Tipo de sangre',
            },
        ),
        migrations.CreateModel(
            name='InsuranceHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Seguro medico',
                'verbose_name_plural': 'Seguros medicos',
            },
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de relacion',
                'verbose_name_plural': 'Tipo de relacion',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('father_lastname', models.CharField(max_length=255)),
                ('mother_lastname', models.CharField(max_length=255)),
                ('cellphone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('no_ine', models.CharField(max_length=255)),
                ('is_emergency_contact', models.BooleanField(default=False)),
                ('curp', models.CharField(max_length=18)),
                ('address_proof', models.FileField(upload_to=efile.models.upload_to_tutor_address_proof)),
                ('ine', models.FileField(upload_to=efile.models.upload_to_tutor_ine)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efile.address')),
                ('relationship_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efile.relationshiptype')),
            ],
            options={
                'verbose_name': 'Tutores',
                'verbose_name_plural': 'Tutores',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('father_lastname', models.CharField(max_length=255)),
                ('mother_lastname', models.CharField(max_length=255)),
                ('curp', models.CharField(max_length=18)),
                ('birthDate', models.DateField()),
                ('birth_certificate', models.FileField(upload_to=efile.models.upload_to_birth_certificate)),
                ('curp_file', models.FileField(upload_to=efile.models.upload_to_curp)),
                ('blood_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='efile.bloodtype')),
                ('insurance_health', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='efile.insurancehealth')),
                ('who_enroll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='efile.relationshiptype')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Efile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_config.academicyear')),
                ('emergency_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_one', to='efile.tutor')),
                ('emergency_three', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_three', to='efile.tutor')),
                ('emergency_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_two', to='efile.tutor')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_config.schoolconfig')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efile.student')),
                ('tutor_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_one', to='efile.tutor')),
                ('tutor_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_two', to='efile.tutor')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
            },
        ),
        migrations.AddConstraint(
            model_name='tutor',
            constraint=models.UniqueConstraint(fields=('curp',), name='unique curp tutors'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('curp',), name='unique curp student'),
        ),
    ]
