# Generated by Django 4.0.3 on 2022-06-01 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('efile', '0002_efile_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Catalogo de ciudades',
                'verbose_name_plural': 'Catalogo de ciudades',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Catalogo de estados',
                'verbose_name_plural': 'Catalogo de estados',
            },
        ),
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Catalogo de colonias',
                'verbose_name_plural': 'Catalogo de colonias',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Catalogo de municipios',
                'verbose_name_plural': 'Catalogo de municipios',
            },
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Catalogo de codigos postales',
                'verbose_name_plural': 'Catalogo de codigos postales',
            },
        ),
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.RemoveField(
            model_name='address',
            name='suburb',
        ),
        migrations.RemoveField(
            model_name='address',
            name='town',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zip_code',
        ),
        migrations.CreateModel(
            name='SepomexCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efile.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efile.state')),
                ('suburb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efile.suburb')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efile.town')),
                ('zip_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efile.zipcode')),
            ],
            options={
                'verbose_name': 'Catalogo de estados',
                'verbose_name_plural': 'Catalogo de estados',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='sepomex_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='efile.sepomexcatalog'),
        ),
    ]
