# Generated by Django 4.0.3 on 2022-06-02 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('efile', '0003_city_state_suburb_town_zipcode_remove_address_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sepomexcatalog',
            options={'verbose_name': 'Catalogo de sepomex', 'verbose_name_plural': 'Catalogo de sepomex'},
        ),
        migrations.AlterField(
            model_name='sepomexcatalog',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='efile.city'),
        ),
    ]
