# Generated by Django 4.0.3 on 2022-06-03 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_config', '0003_grade_group_employee_school_gradegroupconfig_and_more'),
        ('efile', '0004_alter_sepomexcatalog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_config.schoolconfig'),
        ),
    ]
