# Generated by Django 4.0.3 on 2022-06-03 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_config', '0004_employee_email_employee_is_active'),
        ('efile', '0006_student_email_student_grade_group_student_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='efile',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='efile',
            name='school',
        ),
        migrations.AddField(
            model_name='efile',
            name='efile_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_config.efileconfig'),
        ),
    ]
