# Generated by Django 4.0.3 on 2022-06-03 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_config', '0002_position_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=255)),
                ('created_at', models.TimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grados',
                'verbose_name_plural': 'Grados',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=255)),
                ('created_at', models.TimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grupos',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_config.schoolconfig'),
        ),
        migrations.CreateModel(
            name='GradeGroupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_config.grade')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_config.group')),
            ],
            options={
                'verbose_name': 'Configuracion del grado y grupo',
                'verbose_name_plural': 'Configuracion del grado y grupo',
            },
        ),
        migrations.CreateModel(
            name='EfileConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_config.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_config.schoolconfig')),
            ],
            options={
                'verbose_name': 'Configuracion del expediente',
                'verbose_name_plural': 'Configuracion del expediente',
            },
        ),
    ]
