# Generated by Django 4.0.3 on 2022-06-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_config', '0004_employee_email_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='efileconfig',
            name='current_config',
            field=models.BooleanField(default=True),
        ),
    ]
